version: '3'

services:
  stock-prediction:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"  # For Jupyter
      - "8501:8501"  # For Streamlit (if used later)
    environment:
      - PYTHONPATH=/app
